const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
const ui = { score:document.querySelector('#score'), level:document.querySelector('#level'), wave:document.querySelector('#wave'), lives:document.querySelector('#lives'), weapon:document.querySelector('#weapon'), ammo:document.querySelector('#ammo'), icon:document.querySelector('#weaponIcon') };
const message = document.querySelector('#message'), start = document.querySelector('#startButton');
const W=canvas.width,H=canvas.height, keys={}, weapons=[{name:'BATE',ammo:Infinity,damage:2,rate:360,range:65,icon:'▰'},{name:'PISTOLA',ammo:48,damage:2,rate:250,range:550,icon:'▰'},{name:'RIFLE',ammo:72,damage:3,rate:120,range:620,icon:'═'}];
let game, last=0;
addEventListener('keydown',e=>{ keys[e.code]=true; if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault(); if(e.code==='KeyP'&&game?.running){game.paused=!game.paused; announce(game.paused?'PAUSA':'',false)} });
addEventListener('keyup',e=>keys[e.code]=false); start.onclick=reset;
function reset(){game={running:true,paused:false,score:0,level:1,wave:1,lives:3,weapon:0,ammo:weapons.map(w=>w.ammo),player:{x:W/2,y:H-90,r:14,hp:1,dir:-Math.PI/2},zombies:[],shots:[],effects:[],lastShot:0,nextWave:0}; message.classList.add('hidden'); spawnWave(); updateUI(); requestAnimationFrame(loop)}
function updateUI(){let g=game,w=weapons[g.weapon]; ui.score.textContent=String(g.score).padStart(6,'0');ui.level.textContent=String(g.level).padStart(2,'0');ui.wave.textContent=`${String(g.wave).padStart(2,'0')} / ${String(waves()).padStart(2,'0')}`;ui.lives.textContent='♥ '.repeat(g.lives);ui.weapon.textContent=w.name;ui.ammo.textContent=g.ammo[g.weapon]===Infinity?'∞':g.ammo[g.weapon];ui.icon.textContent=w.icon}
function waves(){return 2+game.level}
function spawnWave(){let g=game,isBoss=g.wave===waves(), count=3+g.level*2+g.wave*2; for(let i=0;i<count;i++)spawnZombie(false); if(isBoss)spawnZombie(true); announce(isBoss?'¡JEFE DE HORDA!':`OLEADA ${g.wave}`,true)}
function spawnZombie(boss){let edge=Math.floor(Math.random()*4), x=edge===0?10:edge===1?W-10:Math.random()*W,y=edge===2?10:edge===3?H-10:Math.random()*H;game.zombies.push({x,y,r:boss?28:13,hp:boss?16+game.level*5:2+Math.floor(game.level/2),speed:(boss?24:30)+game.level*4,boss,hit:0})}
function loop(t){let dt=Math.min((t-last)/1000,.04);last=t;if(game?.running&&!game.paused){update(dt,t);draw();requestAnimationFrame(loop)}else if(game?.running){draw();requestAnimationFrame(loop)}}
function update(dt,t){let g=game,p=g.player, mx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),my=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0);if(mx||my){let l=Math.hypot(mx,my);p.x=Math.max(22,Math.min(W-22,p.x+mx/l*180*dt));p.y=Math.max(22,Math.min(H-22,p.y+my/l*180*dt));p.dir=Math.atan2(my,mx)} if(keys.Space)shoot(t);
 for(const z of g.zombies){let a=Math.atan2(p.y-z.y,p.x-z.x),d=Math.hypot(p.x-z.x,p.y-z.y);if(d>p.r+z.r) {z.x+=Math.cos(a)*z.speed*dt;z.y+=Math.sin(a)*z.speed*dt}else if(!z.hit){z.hit=1;hurt()}}
 for(const s of g.shots){s.x+=Math.cos(s.a)*s.v*dt;s.y+=Math.sin(s.a)*s.v*dt;s.life-=dt;for(const z of g.zombies){if(!s.dead&&Math.hypot(s.x-z.x,s.y-z.y)<z.r+5){z.hp-=s.dmg;s.dead=true;z.hit=.12;if(z.hp<=0)kill(z)}}} g.shots=g.shots.filter(s=>s.life>0&&!s.dead);g.zombies=g.zombies.filter(z=>z.hp>0);g.effects=g.effects.filter(e=>e.life>0);if(!g.zombies.length&&!g.nextWave){g.nextWave=t+1300;announce('SECTOR LIMPIO',true)}if(g.nextWave&&t>g.nextWave){g.nextWave=0;if(g.wave<waves()){g.wave++;spawnWave()}else{g.level++;g.wave=1;if((g.level-1)%3===0&&g.weapon<weapons.length-1){g.weapon++;announce(`ARMA DESBLOQUEADA: ${weapons[g.weapon].name}`,true)}spawnWave()}updateUI()}}
function shoot(t){let g=game,w=weapons[g.weapon],p=g.player;if(t-g.lastShot<w.rate||g.ammo[g.weapon]<=0)return;g.lastShot=t;if(g.ammo[g.weapon]!==Infinity)g.ammo[g.weapon]--; if(w.range<100){for(const z of g.zombies){if(Math.hypot(z.x-p.x,z.y-p.y)<w.range){z.hp-=w.damage;z.hit=.18;if(z.hp<=0)kill(z)}}g.effects.push({x:p.x+Math.cos(p.dir)*35,y:p.y+Math.sin(p.dir)*35,life:.1,melee:true})}else g.shots.push({x:p.x,y:p.y,a:p.dir,v:600,dmg:w.damage,life:w.range/600});}
function kill(z){z.hp=0;game.score+=z.boss?500:30;game.effects.push({x:z.x,y:z.y,life:.35})}
function hurt(){let g=game;g.lives--;g.zombies=[];if(g.lives<=0){g.running=false;message.querySelector('h1').innerHTML='MISIÓN<br><span>FALLIDA</span>';message.querySelector('.instructions').innerHTML=`PUNTAJE FINAL: <b>${g.score}</b>`;start.textContent='REINTENTAR';message.classList.remove('hidden')}else {g.player.x=W/2;g.player.y=H-90;announce('¡UNA VIDA MENOS!',true);setTimeout(()=>spawnWave(),700)}}
function announce(text,show){if(!show)return;const a=document.createElement('div');a.className='toast';a.textContent=text;document.querySelector('.arena-wrap').append(a);setTimeout(()=>a.remove(),1050)}
function draw(){ctx.fillStyle='#071009';ctx.fillRect(0,0,W,H); drawGround(); for(const s of game.shots){ctx.fillStyle='#dfff7e';ctx.fillRect(s.x-3,s.y-3,6,6)}for(const z of game.zombies)drawZombie(z);drawPlayer(game.player);for(const e of game.effects){ctx.fillStyle=e.melee?'#c9ff56':'#b9352d';ctx.globalAlpha=e.life*3;ctx.beginPath();ctx.arc(e.x,e.y,e.melee?28:20,0,7);ctx.fill();ctx.globalAlpha=1;e.life-=.02}ctx.fillStyle='#b9d76b';ctx.font='12px monospace';ctx.fillText('ZONA DE CONTENCIÓN // NO DEJES QUE TE RODEEN',18,28)}
function drawGround(){ctx.fillStyle='#0b160d';for(let x=0;x<W;x+=80)for(let y=0;y<H;y+=70){if((x*13+y)%5===0){ctx.fillRect(x+Math.random()*2,y+4,2,2)}}ctx.strokeStyle='#243520';ctx.lineWidth=4;ctx.strokeRect(10,10,W-20,H-20);ctx.strokeStyle='#5c1818';ctx.lineWidth=2;ctx.strokeRect(17,17,W-34,H-34)}
function drawPlayer(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.dir+Math.PI/2);ctx.fillStyle='#c84e32';ctx.fillRect(-9,-17,18,12);ctx.fillStyle='#d5aa70';ctx.fillRect(-7,-7,14,13);ctx.fillStyle='#274936';ctx.fillRect(-10,6,20,16);ctx.fillStyle='#151c18';ctx.fillRect(-12,22,8,6);ctx.fillRect(4,22,8,6);ctx.fillStyle='#d6f16f';ctx.fillRect(-3,-28,6,16);ctx.restore()}
function drawZombie(z){ctx.save();ctx.translate(z.x,z.y);if(z.hit){ctx.fillStyle='#fff';z.hit-=.02}else ctx.fillStyle=z.boss?'#657d37':'#8da547';ctx.fillRect(-z.r*.7,-z.r,z.r*1.4,z.r*1.1);ctx.fillStyle='#4d6c2c';ctx.fillRect(-z.r,-z.r*.1,z.r*2,z.r);ctx.fillStyle='#1b2116';ctx.fillRect(-z.r*.5,-z.r*.62,4,4);ctx.fillRect(z.r*.25,-z.r*.62,4,4);ctx.fillStyle='#8c3030';ctx.fillRect(-z.r*.45,z.r*.1,z.r*.9,3);ctx.fillStyle='#2d3c38';ctx.fillRect(-z.r*.85,z.r*.35,z.r*1.7,z.r*.7);ctx.restore();if(z.boss){ctx.fillStyle='#3a1414';ctx.fillRect(z.x-30,z.y-z.r-13,60,5);ctx.fillStyle='#cf4439';ctx.fillRect(z.x-30,z.y-z.r-13,60*(z.hp/(16+game.level*5)),5)}}
