const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui={score:document.querySelector('#score'),level:document.querySelector('#level'),wave:document.querySelector('#wave'),lives:document.querySelector('#lives'),weapon:document.querySelector('#weapon'),ammo:document.querySelector('#ammo'),ammoBar:document.querySelector('#ammoBar'),icon:document.querySelector('#weaponIcon'),slots:document.querySelector('#weaponSlots'),catStatus:document.querySelector('#catStatus')};
const message=document.querySelector('#message'),start=document.querySelector('#startButton'),W=canvas.width,H=canvas.height,keys={};
const weapons=[
  {name:'BATE',kind:'melee',damage:3,rate:.32,range:72,ammo:Infinity,icon:'▰'},
  {name:'PISTOLA',kind:'bullet',damage:2,rate:.25,range:550,ammo:48,icon:'▰'},
  {name:'ESCOPETA',kind:'shotgun',damage:14,rate:.65,range:150,ammo:8,icon:'▰'},
  {name:'RIFLE',kind:'bullet',damage:3,rate:.12,range:620,ammo:72,icon:'═'}
];
let game=null,lastFrame=0;
addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='KeyP'&&!e.repeat&&game?.running){game.paused=!game.paused;announce(game.paused?'PAUSA':'')}if(e.code==='KeyQ'&&!e.repeat)useCat();if(e.code.startsWith('Digit')&&!e.repeat)switchWeapon(Number(e.code.slice(-1))-1)});
addEventListener('keyup',e=>keys[e.code]=false);start.onclick=handleStart;
function handleStart(){if(game&&!game.running&&game.level===2){game.running=true;message.classList.add('hidden');setLevel(3);requestAnimationFrame(loop)}else startGame()}

function startGame(){
  game={running:true,paused:false,time:0,score:0,level:1,wave:1,lives:3,weapon:0,ammo:weapons.map(w=>w.ammo),lastShot:-99,nextWave:0,zombies:[],shots:[],effects:[],barrels:[],cat:null,tookDamage:false};
  weapons.forEach(w=>w.unlocked=false);weapons[0].unlocked=true;
  setLevel(1);message.classList.add('hidden');requestAnimationFrame(loop);
}
function setLevel(level){
  game.level=level;game.wave=1;game.zombies=[];game.shots=[];game.effects=[];game.barrels=[];game.nextWave=0;game.player={x:W/2,y:H-85,r:14,dir:-Math.PI/2};
  if(level===2){game.weapon=0;game.ammo[0]=Infinity;game.ammo[2]=8;weapons[2].unlocked=true;game.cat={x:W/2-70,y:H-145,target:null,activeUntil:0,cooldownUntil:0};announce('NIVEL 2 · EL CALLEJÓN')}
  else {game.cat=null;if(level===3){weapons[3].unlocked=true;if(game.weapon<3)game.weapon=3}announce(level===1?'NIVEL 1 · SECTOR 07':'NIVEL 3 · ÚLTIMA DEFENSA')}
  spawnWave();updateUI();
}
function totalWaves(){return game.level===2?3:3}
function spawnWave(){
  const count=game.level===2?(game.wave===1?8:game.wave===2?7:21):(3+game.level*2+game.wave*2);
  for(let i=0;i<count;i++)spawnZombie(game.level===2&&game.wave>1&&i%5===0?'riot':'basic');
  if(game.level===3&&game.wave===3)spawnZombie('boss');
  if(game.level===2&&game.wave===2){game.barrels=[{x:230,y:235,armed:true},{x:710,y:370,armed:true},{x:475,y:150,armed:true}];weapons[2].unlocked=true;announce('ESCOPETA DESBLOQUEADA · 8 CARTUCHOS')}
}
function spawnZombie(type){let edge=Math.floor(Math.random()*4),x=edge===0?16:edge===1?W-16:30+Math.random()*(W-60),y=edge===2?16:edge===3?H-16:30+Math.random()*(H-60),boss=type==='boss',riot=type==='riot';game.zombies.push({x,y,r:boss?28:riot?17:13,hp:boss?22:riot?9:2,maxHp:boss?22:riot?9:2,speed:boss?23:riot?30:game.level===2?42:35,type,facing:0,hit:0,distractedUntil:0})}
function loop(frame){const dt=Math.min((frame-lastFrame)/1000,.04);lastFrame=frame;if(game?.running){if(!game.paused)update(dt);draw();requestAnimationFrame(loop)}}
function update(dt){game.time+=dt;const p=game.player,mx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),my=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0);if(mx||my){const l=Math.hypot(mx,my);p.x=Math.max(25,Math.min(W-25,p.x+mx/l*190*dt));p.y=Math.max(25,Math.min(H-25,p.y+my/l*190*dt));p.dir=Math.atan2(my,mx)}if(keys.Space)shoot();if(game.cat&&game.cat.activeUntil>game.time){game.cat.x+=(game.cat.target.x-game.cat.x)*Math.min(1,dt*5);game.cat.y+=(game.cat.target.y-game.cat.y)*Math.min(1,dt*5)}for(const z of game.zombies){const distracted=z.distractedUntil>game.time&&game.cat?.activeUntil>game.time,target=distracted?game.cat:p,a=Math.atan2(target.y-z.y,target.x-z.x),d=Math.hypot(target.x-z.x,target.y-z.y);z.facing=a;if(d>(target===p?p.r+z.r:8)){z.x+=Math.cos(a)*z.speed*dt;z.y+=Math.sin(a)*z.speed*dt}else if(target===p&&!z.hit){z.hit=.3;hurt()}if(z.hit>0)z.hit-=dt}for(const s of game.shots){s.x+=Math.cos(s.angle)*s.speed*dt;s.y+=Math.sin(s.angle)*s.speed*dt;s.life-=dt;for(const z of game.zombies)if(!s.dead&&Math.hypot(s.x-z.x,s.y-z.y)<z.r+6){damage(z,s.damage,false);s.dead=true}for(const b of game.barrels)if(b.armed&&Math.hypot(s.x-b.x,s.y-b.y)<18)explode(b)}game.shots=game.shots.filter(s=>s.life>0&&!s.dead);game.zombies=game.zombies.filter(z=>z.hp>0);game.effects=game.effects.filter(e=>e.life>0);if(!game.zombies.length&&!game.nextWave){game.nextWave=game.time+1.2;announce('SECTOR LIMPIO')}if(game.nextWave&&game.time>game.nextWave){game.nextWave=0;if(game.wave<totalWaves())game.wave++,spawnWave();else finishWave()}updateUI()}
function finishWave(){if(game.level===1){setLevel(2)}else if(game.level===2){game.running=false;const perfect=!game.tookDamage;message.querySelector('h1').innerHTML='NIVEL 2<br><span>SUPERADO</span>';message.querySelector('.instructions').innerHTML=perfect?'¡CHALECO TÁCTICO DESBLOQUEADO!':'El Nivel 3 y su jefe pertenecen al siguiente equipo';start.textContent='CONTINUAR';message.classList.remove('hidden')}else{game.running=false;message.querySelector('h1').innerHTML='MISIÓN<br><span>COMPLETA</span>';start.textContent='JUGAR DE NUEVO';message.classList.remove('hidden')}}
function switchWeapon(i){if(!game||!weapons[i]||!weapons[i].unlocked)return;game.weapon=i;updateUI();announce(`ARMA: ${weapons[i].name}`)}
function shoot(){const w=weapons[game.weapon],p=game.player;if(game.time-game.lastShot<w.rate||game.ammo[game.weapon]<=0)return;game.lastShot=game.time;if(w.ammo!==Infinity)game.ammo[game.weapon]--;if(w.kind==='melee'){for(const z of game.zombies){const d=Math.hypot(z.x-p.x,z.y-p.y),a=Math.atan2(z.y-p.y,z.x-p.x);if(d<w.range&&Math.abs(angleDiff(a,p.dir))<1.15)damage(z,w.damage,true)}game.effects.push({x:p.x+Math.cos(p.dir)*35,y:p.y+Math.sin(p.dir)*35,life:.2,kind:'hit'})}else if(w.kind==='shotgun'){for(const z of game.zombies){const d=Math.hypot(z.x-p.x,z.y-p.y),a=Math.atan2(z.y-p.y,z.x-p.x);if(d<w.range&&Math.abs(angleDiff(a,p.dir))<.8)damage(z,w.damage,false)}game.effects.push({x:p.x+Math.cos(p.dir)*45,y:p.y+Math.sin(p.dir)*45,life:.3,kind:'blast'})}else game.shots.push({x:p.x,y:p.y,angle:p.dir,speed:650,damage:w.damage,life:w.range/650})}
function damage(z,n,melee){if(z.type==='riot'&&melee&&Math.cos(angleDiff(Math.atan2(game.player.y-z.y,game.player.x-z.x),z.facing))>.15)n*=.2;z.hp-=n;z.hit=.12;if(z.hp<=0){game.score+=z.type==='boss'?500:z.type==='riot'?80:30;game.effects.push({x:z.x,y:z.y,life:.4,kind:'death'})}}
function useCat(){if(game?.level!==2||!game.cat||!game.running||game.paused||game.time<game.cat.cooldownUntil)return;const now=game.time;game.cat.cooldownUntil=now+20;game.cat.activeUntil=now+5;game.cat.target={x:100+Math.random()*(W-200),y:100+Math.random()*(H-200)};const riot=game.zombies.find(z=>z.type==='riot'),targets=riot?[riot]:game.zombies.filter(z=>z.type==='basic').slice(0,4);for(const z of targets)z.distractedUntil=now+5;game.effects.push({x:game.cat.target.x,y:game.cat.target.y,life:1.5,kind:'bell'});announce('¡MIAU! ZOMBIS ATRAÍDOS 5s')}
function hurt(){game.tookDamage=true;game.lives--;game.zombies=[];if(game.lives<=0){game.running=false;message.querySelector('h1').innerHTML='MISIÓN<br><span>FALLIDA</span>';start.textContent='REINTENTAR';message.classList.remove('hidden')}else{game.player.x=W/2;game.player.y=H-85;announce('¡UNA VIDA MENOS!');setTimeout(()=>spawnWave(),500)}}
function explode(b){if(!b.armed)return;b.armed=false;game.effects.push({x:b.x,y:b.y,life:.7,kind:'explosion'});for(const z of game.zombies)if(Math.hypot(z.x-b.x,z.y-b.y)<100)damage(z,8,false)}
function updateUI(){if(!game)return;const w=weapons[game.weapon],locked=game.level!==2,ammo=w.ammo===Infinity?'∞':game.ammo[game.weapon],ratio=w.ammo===Infinity?1:Math.max(0,game.ammo[game.weapon]/w.ammo);ui.score.textContent=String(game.score).padStart(6,'0');ui.level.textContent=String(game.level).padStart(2,'0');ui.wave.textContent=`${String(game.wave).padStart(2,'0')} / 03`;ui.lives.textContent='♥ '.repeat(game.lives)||'—';ui.weapon.textContent=w.name;ui.ammo.textContent=ammo;ui.ammoBar.style.width=`${ratio*100}%`;ui.ammoBar.style.background=ratio<.25?'#ff473d':'var(--acid)';ui.icon.textContent=w.icon;ui.slots.innerHTML=weapons.map((x,i)=>`<span class="weapon-slot ${i===game.weapon?'active':''} ${x.unlocked?'':'locked'}"><b>${i+1}</b> ${x.name} ${x.unlocked?(x.ammo===Infinity?'∞':game.ammo[i]):'🔒'}</span>`).join('');ui.catStatus.textContent=locked?'COMPAÑERO: NIVEL 2':game.cat?game.time<game.cat.cooldownUntil?`Q · RECARGA ${Math.ceil(game.cat.cooldownUntil-game.time)}s`:'Q · DISTRAER LISTO':'COMPAÑERO INACTIVO'}
function announce(text){const a=document.createElement('div');a.className='toast';a.textContent=text;document.querySelector('.arena-wrap').append(a);setTimeout(()=>a.remove(),1100)}
function draw(){ctx.fillStyle=game.level===2?(game.wave===3?'#15120d':'#0b160d'):'#071009';ctx.fillRect(0,0,W,H);ctx.strokeStyle=game.level===2?'#9a692e':'#243520';ctx.lineWidth=5;ctx.strokeRect(10,10,W-20,H-20);if(game.level===2&&game.wave===3){ctx.fillStyle='#302b25';for(let x=90;x<900;x+=180){ctx.fillRect(x,130+(x%140),88,38);ctx.fillStyle='#0b0d0c';ctx.fillRect(x+12,122+(x%140),24,8);ctx.fillRect(x+52,122+(x%140),24,8);ctx.fillStyle='#302b25'}}for(const b of game.barrels)if(b.armed)drawBarrel(b);for(const s of game.shots){ctx.fillStyle='#dfff7e';ctx.fillRect(s.x-3,s.y-3,6,6)}for(const z of game.zombies)drawZombie(z);if(game.cat)drawCat(game.cat);drawPlayer(game.player);for(const e of game.effects){e.life-=.02;drawEffect(e)}ctx.fillStyle='#b9d76b';ctx.font='12px monospace';ctx.fillText(`NIVEL ${game.level} // ${game.level===2?'GATO GORDO ACTIVO':'SECTOR DE CONTENCIÓN'}`,18,28)}
function drawPlayer(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.dir+Math.PI/2);ctx.fillStyle='#c84e32';ctx.fillRect(-9,-17,18,12);ctx.fillStyle='#d5aa70';ctx.fillRect(-7,-7,14,13);ctx.fillStyle='#274936';ctx.fillRect(-10,6,20,16);ctx.fillStyle='#151c18';ctx.fillRect(-12,22,8,6);ctx.fillRect(4,22,8,6);ctx.restore()}
function drawCat(c){ctx.save();ctx.translate(c.x,c.y);ctx.fillStyle='#aa835e';ctx.beginPath();ctx.ellipse(0,2,25,18,0,0,7);ctx.fill();ctx.beginPath();ctx.arc(-17,-11,15,0,7);ctx.fill();ctx.fillStyle='#292015';ctx.fillRect(-24,-19,4,4);ctx.fillRect(-13,-19,4,4);ctx.fillStyle='#d5be61';ctx.fillRect(14,3,16,3);ctx.fillStyle='#f1e7a0';ctx.font='9px monospace';ctx.textAlign='center';ctx.fillText('GATO',0,31);ctx.restore();if(c.activeUntil>game.time){ctx.strokeStyle='#e7d36b';ctx.lineWidth=3;for(let r=12;r<32;r+=8)ctx.strokeRect(c.x-r,c.y-r,r*2,r*2)}}
function drawZombie(z){ctx.save();ctx.translate(z.x,z.y);ctx.fillStyle=z.hit>0?'#fff':z.type==='boss'?'#6b3340':z.type==='riot'?'#536172':'#8da547';ctx.fillRect(-z.r*.7,-z.r,z.r*1.4,z.r*1.1);ctx.fillStyle=z.type==='riot'?'#31445a':z.type==='boss'?'#3c1b2a':'#4d6c2c';ctx.fillRect(-z.r,-z.r*.1,z.r*2,z.r);ctx.fillStyle='#1b2116';ctx.fillRect(-z.r*.5,-z.r*.62,4,4);ctx.fillRect(z.r*.25,-z.r*.62,4,4);if(z.type==='riot'){ctx.fillStyle='#aeb8c5';ctx.fillRect(-z.r,-z.r-5,z.r*2,5);ctx.fillStyle='#d5a83a';ctx.fillRect(-z.r*.8,z.r*.25,z.r*1.6,5)}ctx.restore();if(z.type==='riot'||z.type==='boss'){ctx.fillStyle='#341719';ctx.fillRect(z.x-20,z.y-z.r-15,40,4);ctx.fillStyle='#cf4439';ctx.fillRect(z.x-20,z.y-z.r-15,40*Math.max(0,z.hp/z.maxHp),4)}}
function drawBarrel(b){ctx.fillStyle='#9e4b28';ctx.fillRect(b.x-10,b.y-15,20,30);ctx.fillStyle='#f0c24d';ctx.fillRect(b.x-7,b.y-3,14,6)}function drawEffect(e){ctx.globalAlpha=Math.max(0,e.life);ctx.strokeStyle=e.kind==='bell'?'#f3df68':e.kind==='explosion'?'#ff5b32':'#c9ff56';ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,e.kind==='explosion'?40:20+(1-e.life)*30,0,7);ctx.stroke();ctx.globalAlpha=1}function angleDiff(a,b){return Math.atan2(Math.sin(a-b),Math.cos(a-b))}
