const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui={score:document.querySelector('#score'),level:document.querySelector('#level'),wave:document.querySelector('#wave'),lives:document.querySelector('#lives'),weapon:document.querySelector('#weapon'),ammo:document.querySelector('#ammo'),icon:document.querySelector('#weaponIcon'),slots:document.querySelector('#weaponSlots'),catStatus:document.querySelector('#catStatus')};
const message=document.querySelector('#message'),start=document.querySelector('#startButton'),W=canvas.width,H=canvas.height,keys={};
const weapons=[{name:'BATE',damage:4,rate:320,range:76,icon:'▰',ammo:Infinity,kind:'melee',unlocked:true},{name:'ESCOPETA',damage:14,rate:650,range:150,icon:'▰',ammo:8,kind:'shotgun',unlocked:false},{name:'RIFLE',damage:3,rate:120,range:620,icon:'═',ammo:72,kind:'rifle',unlocked:false}];
const phases=[{name:'EL CALLEJÓN',basic:8,riot:0},{name:'LA INTERSECCIÓN',basic:5,riot:2},{name:'EL BULEVAR BLOQUEADO',basic:13,riot:8}];
let game,last=0;
addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='KeyP'&&game?.running){game.paused=!game.paused;announce(game.paused?'PAUSA':'')}if(e.code==='KeyQ')distract();if(e.code.startsWith('Digit'))selectWeapon(Number(e.code.slice(-1))-1)});
addEventListener('keyup',e=>keys[e.code]=false);start.onclick=reset;
function reset(){game={running:true,paused:false,score:0,level:2,phase:0,lives:3,weapon:0,ammo:weapons.map(w=>w.ammo),lastShot:0,nextPhase:0,tookDamage:false,zombies:[],shots:[],effects:[],barrels:[],cat:{x:W/2,y:H/2,activeUntil:0,cooldownUntil:0,target:null},player:{x:W/2,y:H-85,r:14,dir:-Math.PI/2}};weapons[1].unlocked=false;weapons[2].unlocked=false;message.querySelector('h1').innerHTML='ZOMBIE<br><span>SIEGE</span>';message.querySelector('.instructions').innerHTML='MUÉVETE CON <b>W A S D</b> O <b>FLECHAS</b><br>ATACA CON <b>ESPACIO</b> · COMPAÑERO <b>Q</b>';start.textContent='INICIAR MISIÓN';message.classList.add('hidden');spawnPhase();updateUI();requestAnimationFrame(loop)}
function updateUI(){let w=weapons[game.weapon],remaining=Math.max(0,Math.ceil((game.cat.cooldownUntil-performance.now())/1000));ui.score.textContent=String(game.score).padStart(6,'0');ui.level.textContent='02';ui.wave.textContent=`${String(game.phase+1).padStart(2,'0')} / 03`;ui.lives.textContent='♥ '.repeat(game.lives)||'—';ui.weapon.textContent=w.name;ui.ammo.textContent=w.ammo===Infinity?'∞':game.ammo[game.weapon];ui.icon.textContent=w.icon;ui.slots.innerHTML=weapons.map((x,i)=>`<span class="weapon-slot ${i===game.weapon?'active':''} ${x.unlocked?'':'locked'}"><b>${i+1}</b> ${x.name} ${x.unlocked?(x.ammo===Infinity?'∞':game.ammo[i]):'🔒'}</span>`).join('');ui.catStatus.textContent=remaining?`Q · RECARGA ${remaining}s`:'Q · DISTRAER LISTO'}
function spawnPhase(){let p=phases[game.phase];for(let i=0;i<p.basic;i++)spawnZombie('basic');for(let i=0;i<p.riot;i++)spawnZombie('riot');if(game.phase===1){weapons[1].unlocked=true;announce('ESCOPETA ENCONTRADA · 8 CARTUCHOS');game.barrels=[{x:230,y:235,armed:true},{x:710,y:370,armed:true},{x:475,y:150,armed:true}]}announce(p.name)}
function spawnZombie(type){let edge=Math.floor(Math.random()*4),x=edge===0?16:edge===1?W-16:30+Math.random()*(W-60),y=edge===2?16:edge===3?H-16:30+Math.random()*(H-60),riot=type==='riot';game.zombies.push({x,y,r:riot?17:13,hp:riot?9:2,maxHp:riot?9:2,speed:riot?30:42,type,facing:0,hit:0,distractedUntil:0})}
function loop(t){let dt=Math.min((t-last)/1000,.04);last=t;if(game?.running&&!game.paused)update(dt,t);if(game?.running){draw();requestAnimationFrame(loop)}}
function update(dt,t){let p=game.player,mx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),my=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0);if(mx||my){let l=Math.hypot(mx,my);p.x=Math.max(25,Math.min(W-25,p.x+mx/l*190*dt));p.y=Math.max(25,Math.min(H-25,p.y+my/l*190*dt));p.dir=Math.atan2(my,mx)}if(keys.Space)shoot(t);if(game.cat.activeUntil>t){let c=game.cat;c.x+=(c.target.x-c.x)*Math.min(1,dt*5);c.y+=(c.target.y-c.y)*Math.min(1,dt*5)}for(let z of game.zombies){let attracted=z.distractedUntil>t&&game.cat.activeUntil>t,target=attracted?game.cat:p,a=Math.atan2(target.y-z.y,target.x-z.x),d=Math.hypot(target.x-z.x,target.y-z.y);z.facing=a;if(d>(target===p?p.r+z.r:8)){z.x+=Math.cos(a)*z.speed*dt;z.y+=Math.sin(a)*z.speed*dt}else if(target===p&&!z.hit){z.hit=.3;hurt()}if(z.hit>0)z.hit-=dt}for(let s of game.shots){s.x+=Math.cos(s.angle)*s.speed*dt;s.y+=Math.sin(s.angle)*s.speed*dt;s.life-=dt;for(let z of game.zombies)if(!s.dead&&Math.hypot(s.x-z.x,s.y-z.y)<z.r+6){damageZombie(z,s.damage,false);s.dead=true}for(let b of game.barrels)if(b.armed&&Math.hypot(s.x-b.x,s.y-b.y)<18)explodeBarrel(b)}game.shots=game.shots.filter(s=>s.life>0&&!s.dead);game.zombies=game.zombies.filter(z=>z.hp>0);game.effects=game.effects.filter(e=>e.life>0);if(!game.zombies.length&&!game.nextPhase){game.nextPhase=t+1500;announce(game.phase===2?'SALIDA DESPEJADA':'SECTOR LIMPIO')}if(game.nextPhase&&t>game.nextPhase){game.nextPhase=0;if(game.phase<2){game.phase++;spawnPhase()}else completeLevel()}updateUI()}
function selectWeapon(i){if(!game||!weapons[i]?.unlocked)return;game.weapon=i;updateUI();announce(`ARMA: ${weapons[i].name}`)}
function shoot(t){let w=weapons[game.weapon],p=game.player;if(t-game.lastShot<w.rate||game.ammo[game.weapon]<=0)return;game.lastShot=t;if(game.ammo[game.weapon]!==Infinity)game.ammo[game.weapon]--;if(w.kind==='melee'){for(let z of game.zombies){let d=Math.hypot(z.x-p.x,z.y-p.y),a=Math.atan2(z.y-p.y,z.x-p.x);if(d<w.range&&Math.abs(diff(a,p.dir))<1.15)damageZombie(z,w.damage,true)}game.effects.push({x:p.x+Math.cos(p.dir)*38,y:p.y+Math.sin(p.dir)*38,life:.18,kind:'hit'})}else if(w.kind==='shotgun'){for(let z of game.zombies){let d=Math.hypot(z.x-p.x,z.y-p.y),a=Math.atan2(z.y-p.y,z.x-p.x);if(d<w.range&&Math.abs(diff(a,p.dir))<.8)damageZombie(z,w.damage,false)}game.effects.push({x:p.x+Math.cos(p.dir)*46,y:p.y+Math.sin(p.dir)*46,life:.3,kind:'blast'})}else game.shots.push({x:p.x,y:p.y,angle:p.dir,speed:650,damage:w.damage,life:w.range/650})}
function damageZombie(z,n,melee){if(z.type==='riot'&&melee&&front(z,game.player))n*=.2;z.hp-=n;z.hit=.14;if(z.hp<=0){game.score+=z.type==='riot'?80:30;game.effects.push({x:z.x,y:z.y,life:.4,kind:'death'})}}
function front(z,p){return Math.cos(diff(Math.atan2(p.y-z.y,p.x-z.x),z.facing))>.15}function diff(a,b){return Math.atan2(Math.sin(a-b),Math.cos(a-b))}
function distract(){if(!game?.running||game.paused||performance.now()<game.cat.cooldownUntil)return;let now=performance.now();game.cat.cooldownUntil=now+20000;game.cat.activeUntil=now+4000;game.cat.target={x:100+Math.random()*(W-200),y:100+Math.random()*(H-200)};let basic=game.zombies.filter(z=>z.type==='basic').slice(0,4),riot=game.zombies.find(z=>z.type==='riot');(riot?[riot]:basic).forEach(z=>z.distractedUntil=now+4000);game.effects.push({x:game.cat.target.x,y:game.cat.target.y,life:1.8,kind:'bell'});announce(`¡MIAU! ${riot?'ANTIDISTURBIOS DISTRAÍDO':'HASTA 4 ZOMBIS DISTRAÍDOS'}`)}
function explodeBarrel(b){if(!b.armed)return;b.armed=false;game.effects.push({x:b.x,y:b.y,life:.7,kind:'explosion'});for(let z of game.zombies)if(Math.hypot(z.x-b.x,z.y-b.y)<100)damageZombie(z,8,false)}
function hurt(){game.tookDamage=true;game.lives--;game.zombies=[];game.cat.activeUntil=0;if(game.lives<=0){game.running=false;message.querySelector('h1').innerHTML='MISIÓN<br><span>FALLIDA</span>';message.querySelector('.instructions').innerHTML=`PUNTAJE FINAL: <b>${game.score}</b>`;start.textContent='REINTENTAR';message.classList.remove('hidden')}else{game.player.x=W/2;game.player.y=H-85;announce('¡UNA VIDA MENOS!');setTimeout(spawnPhase,700)}}
function completeLevel(){game.running=false;let vest=!game.tookDamage;message.querySelector('h1').innerHTML='NIVEL 2<br><span>SUPERADO</span>';message.querySelector('.instructions').innerHTML=vest?'¡PERFECTO! DESBLOQUEASTE EL <b>CHALECO TÁCTICO</b><br>ABSORBE 2 GOLPES EN EL NIVEL 3':`PUNTAJE FINAL: <b>${game.score}</b><br>El jefe te espera en el Nivel 3`;start.textContent='JUGAR DE NUEVO';message.classList.remove('hidden')}
function announce(text){let a=document.createElement('div');a.className='toast';a.textContent=text;document.querySelector('.arena-wrap').append(a);setTimeout(()=>a.remove(),1100)}
function draw(){ctx.fillStyle='#071009';ctx.fillRect(0,0,W,H);drawGround();for(let b of game.barrels)if(b.armed)drawBarrel(b);for(let s of game.shots){ctx.fillStyle='#dfff7e';ctx.fillRect(s.x-3,s.y-3,6,6)}for(let z of game.zombies)drawZombie(z);drawCat(game.cat);drawPlayer(game.player);for(let e of game.effects){e.life-=.02;drawEffect(e)}ctx.fillStyle='#b9d76b';ctx.font='12px monospace';ctx.fillText(`NIVEL 2 // ${phases[game.phase]?.name||'SALIDA'}`,18,28)}
function drawGround(){ctx.fillStyle=game.phase===2?'#12130d':'#0b160d';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#243520';ctx.lineWidth=4;ctx.strokeRect(10,10,W-20,H-20);ctx.strokeStyle='#5c1818';ctx.lineWidth=2;ctx.strokeRect(17,17,W-34,H-34);for(let x=30;x<W;x+=90){ctx.fillStyle='#1b2418';ctx.fillRect(x,75+(x%110),45,8)}}
function drawBarrel(b){ctx.fillStyle='#9e4b28';ctx.fillRect(b.x-10,b.y-15,20,30);ctx.fillStyle='#f0c24d';ctx.fillRect(b.x-7,b.y-3,14,6)}
function drawPlayer(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.dir+Math.PI/2);ctx.fillStyle='#c84e32';ctx.fillRect(-9,-17,18,12);ctx.fillStyle='#d5aa70';ctx.fillRect(-7,-7,14,13);ctx.fillStyle='#274936';ctx.fillRect(-10,6,20,16);ctx.fillStyle='#151c18';ctx.fillRect(-12,22,8,6);ctx.fillRect(4,22,8,6);ctx.fillStyle='#d6f16f';ctx.fillRect(-3,-28,6,16);ctx.restore()}
function drawCat(c){ctx.save();ctx.translate(c.x,c.y);ctx.fillStyle='#aa835e';ctx.beginPath();ctx.ellipse(0,2,22,16,0,0,7);ctx.fill();ctx.beginPath();ctx.arc(-15,-10,14,0,7);ctx.fill();ctx.fillStyle='#292015';ctx.fillRect(-22,-18,4,4);ctx.fillRect(-12,-18,4,4);ctx.fillStyle='#d5be61';ctx.fillRect(13,3,15,3);ctx.restore();if(c.activeUntil>performance.now()){ctx.strokeStyle='#e7d36b';ctx.lineWidth=3;for(let r=12;r<32;r+=8)ctx.strokeRect(c.x-r,c.y-r,r*2,r*2)}}
function drawZombie(z){ctx.save();ctx.translate(z.x,z.y);ctx.fillStyle=z.hit>0?'#fff':z.type==='riot'?'#536172':'#8da547';ctx.fillRect(-z.r*.7,-z.r,z.r*1.4,z.r*1.1);ctx.fillStyle=z.type==='riot'?'#31445a':'#4d6c2c';ctx.fillRect(-z.r,-z.r*.1,z.r*2,z.r);ctx.fillStyle='#1b2116';ctx.fillRect(-z.r*.5,-z.r*.62,4,4);ctx.fillRect(z.r*.25,-z.r*.62,4,4);ctx.fillStyle='#8c3030';ctx.fillRect(-z.r*.45,z.r*.1,z.r*.9,3);if(z.type==='riot'){ctx.fillStyle='#aeb8c5';ctx.fillRect(-z.r,-z.r-5,z.r*2,5);ctx.fillStyle='#d5a83a';ctx.fillRect(-z.r*.8,z.r*.25,z.r*1.6,5)}ctx.restore();if(z.distractedUntil>performance.now()){ctx.strokeStyle='#f3df68';ctx.beginPath();ctx.arc(z.x,z.y-z.r-12,8,0,5);ctx.stroke()}if(z.type==='riot'){ctx.fillStyle='#341719';ctx.fillRect(z.x-18,z.y-z.r-15,36,4);ctx.fillStyle='#cf4439';ctx.fillRect(z.x-18,z.y-z.r-15,36*Math.max(0,z.hp/z.maxHp),4)}}
function drawEffect(e){ctx.globalAlpha=Math.max(0,e.life);ctx.strokeStyle=e.kind==='bell'?'#f3df68':e.kind==='explosion'?'#ff5b32':'#c9ff56';ctx.lineWidth=4;ctx.beginPath();ctx.arc(e.x,e.y,e.kind==='explosion'?40:20+(1-e.life)*30,0,7);ctx.stroke();ctx.globalAlpha=1}
